#!/bin/bash
YUM_REPO_DIR="/etc/yum.repos.d"

repo_files=($(ls $YUM_REPO_DIR/*.repo 2>/dev/null))

[[ ${#repo_files[@]} -eq 0 ]] && cat > $YUM_REPO_DIR/centos6-latest.repo <<EOF
[base]
name=CentOS-6 - Base
mirrorlist=http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os
#baseurl=http://mirror.centos.org/centos/6/os/x86_64/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6

#released updates 
[updates]
name=CentOS-6 - Updates
mirrorlist=http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=updates
#baseurl=http://mirror.centos.org/centos/6/updates/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
EOF

exit 0
