#!/bin/bash
# The base image created by kiwi does not contain an initrd so create one
# here.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

install -m 0644 -o root -g root $(dirname $0)/../bin/update-extlinux.conf /etc/init
