#!/bin/bash
cat >/etc/cloud/cloud.cfg.d/99-openstack-datasource.cfg <<EOL
#cloud-config
datasource:
 OpenStack:
  metadata_urls: ["http://169.254.169.254"]
  max_wait: -1
  timeout: 10
  retries: 5
EOL