#!/bin/bash
YUM_REPO_DIR="/etc/yum.repos.d"

repo_files=($(ls $YUM_REPO_DIR/*.repo 2>/dev/null))

[[ ${#repo_files[@]} -eq 0 ]] && cat > $YUM_REPO_DIR/sl7-latest.repo <<EOF
[base]
name=Scientific Linux 7 - base
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/os
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/os/RPM-GPG-KEY-sl

[updates-fastbugs]
name=Scientific Linux 6 - Updates (fastbugs)
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/updates/fastbugs
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/os/RPM-GPG-KEY-sl

[updates-security]
name=Scientific Linux 6 - Updates (security)
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/updates/security
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/7/x86_64/os/RPM-GPG-KEY-sl
EOF

exit 0

