#!/bin/bash

set -eu
set -o pipefail

cat << EOF > /etc/yum.repos.d/sl6-latest.repo
[base]
name=Scientific Linux 6 - base
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/os
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/os/RPM-GPG-KEY-sl6

[updates-fastbugs]
name=Scientific Linux 6 - Updates (fastbugs)
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/updates/fastbugs
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/os/RPM-GPG-KEY-sl6

[updates-security]
name=Scientific Linux 6 - Updates (security)
baseurl=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/updates/security
gpgcheck=1
gpgkey=http://www.nic.funet.fi/pub/Linux/INSTALL/scientific/6/x86_64/os/RPM-GPG-KEY-sl6
EOF
